// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacie2.Models;

#nullable disable

namespace Pharmacie2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008203936_CorrectionLibelleMvola")]
    partial class CorrectionLibelleMvola
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Pharmacie2.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLivraisonPrevue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("TEXT");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoteCommande")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("commandes");
                });

            modelBuilder.Entity("Pharmacie2.Models.DepenseAnnexe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDepense")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DepensesAnnexes");
                });

            modelBuilder.Entity("Pharmacie2.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("fournisseur");
                });

            modelBuilder.Entity("Pharmacie2.Models.LigneCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixAchatUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantiteRecue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LigneCommandes");
                });

            modelBuilder.Entity("Pharmacie2.Models.LigneVente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantiteUnites")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniteVendue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("VenteId");

                    b.ToTable("LigneVentes");
                });

            modelBuilder.Entity("Pharmacie2.Models.Mutuel", b =>
                {
                    b.Property<int>("IdMutuel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomEmployeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxPriseEnCharge")
                        .HasColumnType("TEXT");

                    b.Property<string>("telephoneEmployeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMutuel");

                    b.ToTable("mutuels");
                });

            modelBuilder.Entity("Pharmacie2.Models.MutuelPaiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MutuelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MutuelId");

                    b.HasIndex("UserId");

                    b.HasIndex("VenteId");

                    b.ToTable("MutuelPaiements");
                });

            modelBuilder.Entity("Pharmacie2.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VenteId");

                    b.ToTable("paiement");
                });

            modelBuilder.Entity("Pharmacie2.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Indication")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MargeBeneficiaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifVerification")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbFoisParJour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NbUniteParBoite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Posologie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantiteEnStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StockAVerifier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniteVente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitesManquantesEstimees")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.ToTable("produits");
                });

            modelBuilder.Entity("Pharmacie2.Models.SessionCaisse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentaireCloture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FondOuverture")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MontantCompteCloture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SessionsCaisse");
                });

            modelBuilder.Entity("Pharmacie2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BlocageCleJusqua")
                        .HasColumnType("TEXT");

                    b.Property<string>("CleSecoursHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("EssaisCleEchoues")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Pharmacie2.Models.Vente", b =>
                {
                    b.Property<int>("IdVente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateVente")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatriculeEmploye")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantEspeces")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantMutuelle")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantRendu")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifAchat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoyenPaiement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MutuelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MutuelleReglee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxMutuelle")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelephoneClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("numeroVente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdVente");

                    b.HasIndex("MutuelId");

                    b.HasIndex("UserId");

                    b.ToTable("ventes");
                });

            modelBuilder.Entity("Pharmacie2.Models.Commande", b =>
                {
                    b.HasOne("Pharmacie2.Models.Fournisseur", "Fournisseur")
                        .WithMany("Commandes")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("Pharmacie2.Models.DepenseAnnexe", b =>
                {
                    b.HasOne("Pharmacie2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pharmacie2.Models.LigneCommande", b =>
                {
                    b.HasOne("Pharmacie2.Models.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pharmacie2.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Pharmacie2.Models.LigneVente", b =>
                {
                    b.HasOne("Pharmacie2.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pharmacie2.Models.Vente", "Vente")
                        .WithMany("Lignes")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("Pharmacie2.Models.MutuelPaiement", b =>
                {
                    b.HasOne("Pharmacie2.Models.Mutuel", "Mutuel")
                        .WithMany()
                        .HasForeignKey("MutuelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Pharmacie2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pharmacie2.Models.Vente", "Vente")
                        .WithMany()
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mutuel");

                    b.Navigation("User");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("Pharmacie2.Models.Paiement", b =>
                {
                    b.HasOne("Pharmacie2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pharmacie2.Models.Vente", "Vente")
                        .WithMany("Paiements")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("Pharmacie2.Models.Produit", b =>
                {
                    b.HasOne("Pharmacie2.Models.Fournisseur", "Fournisseur")
                        .WithMany("Produits")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("Pharmacie2.Models.SessionCaisse", b =>
                {
                    b.HasOne("Pharmacie2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pharmacie2.Models.Vente", b =>
                {
                    b.HasOne("Pharmacie2.Models.Mutuel", "Mutuel")
                        .WithMany()
                        .HasForeignKey("MutuelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pharmacie2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mutuel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pharmacie2.Models.Commande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Pharmacie2.Models.Fournisseur", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Pharmacie2.Models.Vente", b =>
                {
                    b.Navigation("Lignes");

                    b.Navigation("Paiements");
                });
#pragma warning restore 612, 618
        }
    }
}
